image: docker:latest

# When using dind, it's wise to use the overlayfs driver for
# improved performance.
variables:
  DOCKER_DRIVER: overlay2

services:
- docker:dind

before_script:
- docker info
- docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

after_script:
- docker images

build sentry:
  stage: build
  script:
  - docker build --pull --tag $CI_REGISTRY_IMAGE .
  - docker push $CI_REGISTRY_IMAGE:latest

build sentry9:
  stage: build
  script:
  - docker build --build-arg VERSION=9 --pull --tag $CI_REGISTRY_IMAGE:9 .
  - docker push $CI_REGISTRY_IMAGE:9
