# NOTE: This docker-compose.yml is meant to be just an example of how
# you could accomplish this on your own. It is not intended to work in
# all use-cases and must be adapted to fit your needs. This is merely
# a guideline.

# See docs.getsentry.com/on-premise/server/ for full
# instructions
# Generate secret key :
# docker-compose run --rm web config generate-secret-key
# Upgrade db :
# docker-compose run --rm web upgrade

version: '2'
services:
  base:
    restart: always
    build: .
    environment:
      # Run `docker-compose run web config generate-secret-key`
      # to get the SENTRY_SECRET_KEY value.
      SENTRY_SECRET_KEY: 
      SENTRY_MEMCACHED_HOST: memcached
      SENTRY_REDIS_HOST: redis
      SENTRY_POSTGRES_HOST: postgres
      SENTRY_EMAIL_HOST: smtp

    volumes:
      - sentry:/var/lib/sentry/files

  smtp:
    restart: always
    image: tianon/exim4

  memcached:
    restart: always
    image: memcached:1.4

  redis:
    restart: always
    image: redis:3.2-alpine

  postgres:
    restart: always
    image: postgres:9.5
    volumes:
      - db:/var/lib/postgresql/data

  web:
    restart: always
    extends: base
    links:
      - redis
      - postgres
      - memcached
      - smtp
    environment:
      VIRTUAL_PROTO: http
      VIRTUAL_HOST: localhost
      VIRTUAL_PORT: 9000
    ports:
      - '9000:9000'

  cron:
    restart: always
    extends: base
    command: run cron
    links:
      - redis
      - postgres
      - memcached
      - smtp

  worker:
    restart: always
    extends: base
    command: run worker
    links:
      - redis
      - postgres
      - memcached
      - smtp

volumes:
  db: {}
  sentry: {}